/** Good House Co. booking: chat is optional guidance; structured details live in the separate booking sheet. */
import { FormEvent, useEffect, useRef, useState } from "react";

type Field = { label: string; options: string[] };
type Flow = { service: string; matches: string[]; startingPrice: number; time: string; detail: string; payment: string; fields: Field[] };
type ChatMessage = { kind: "guide" | "user"; text: string; id: number; flow?: Flow };

const flows: Flow[] = [
  { service: "Home cleaning", matches: ["clean", "carpet"], startingPrice: 189, time: "Tomorrow · 1–3 PM", detail: "Supplies included", payment: "Pay at booking", fields: [{ label: "Cleaning type", options: ["Standard reset", "Deep clean", "Move-in / move-out"] }, { label: "Home size", options: ["Studio / 1 bed", "2–3 bedrooms", "4+ bedrooms"] }] },
  { service: "TV mounting", matches: ["tv", "television", "soundbar", "mount"], startingPrice: 149, time: "Tomorrow · 1:00 PM", detail: "Wall and mount details reviewed", payment: "Pay at booking", fields: [{ label: "TV size", options: ["Up to 43 inches", "44–65 inches", "Over 65 inches"] }, { label: "Wall mount", options: ["I have one", "I need one", "Not sure"] }] },
  { service: "Furniture assembly", matches: ["furniture", "assembly", "assemble", "bed", "desk", "dresser"], startingPrice: 129, time: "Tomorrow · 3:00 PM", detail: "Item count and setup location confirmed", payment: "Pay at booking", fields: [{ label: "Item type", options: ["Bed or bedroom piece", "Desk or workspace", "Storage or shelving"] }, { label: "Item count", options: ["One item", "Two or three", "Four or more"] }] },
  { service: "Handyman visit", matches: ["handyman", "repair", "hanging", "shelf", "patch", "drywall", "hardware"], startingPrice: 179, time: "Saturday · 9:30 AM", detail: "Two-hour service window", payment: "Approve final scope before charge", fields: [{ label: "Job type", options: ["Small repair", "Hanging or mounting", "Patch, caulk, or touch-up"] }, { label: "Job count", options: ["One task", "A short list", "A few rooms’ worth"] }] },
  { service: "Plumbing help", matches: ["plumb", "faucet", "drain", "toilet", "leak"], startingPrice: 169, time: "Tomorrow · 10:00 AM", detail: "Diagnostic visit", payment: "Approve work after diagnosis", fields: [{ label: "Issue", options: ["Faucet or fixture", "Drain issue", "Toilet issue"] }, { label: "Urgency", options: ["Today if possible", "This week", "Not urgent"] }] },
  { service: "Electrical & lighting", matches: ["electrical", "light", "outlet", "fixture", "switch", "fan"], startingPrice: 159, time: "Thursday · 2:00 PM", detail: "Installation details confirmed", payment: "Approve final scope before charge", fields: [{ label: "Project", options: ["Light fixture", "Outlet or switch", "Ceiling fan or device"] }, { label: "Equipment", options: ["I have it", "I need guidance", "Not sure"] }] },
  { service: "Interior painting", matches: ["paint", "painting", "wall color"], startingPrice: 219, time: "This week · Consultation", detail: "Written quote before payment", payment: "Quote first · no charge today", fields: [{ label: "Scope", options: ["Accent wall", "One room", "Multiple rooms"] }, { label: "Color", options: ["Chosen", "Need guidance", "Not yet chosen"] }] },
  { service: "Moving help", matches: ["move", "moving", "unload", "load", "couch"], startingPrice: 199, time: "Saturday · 11:00 AM", detail: "Two-person crew", payment: "Pay at booking", fields: [{ label: "Move size", options: ["A few items", "Studio / one room", "One to two rooms"] }, { label: "Help needed", options: ["Loading", "Unloading", "In-home moving"] }] },
  { service: "Lawn & yard care", matches: ["lawn", "yard", "mow", "trimming", "garden"], startingPrice: 99, time: "Friday · 9–11 AM", detail: "Routine yard visit", payment: "Pay at booking", fields: [{ label: "Service", options: ["Mowing", "Trimming", "Seasonal cleanup"] }, { label: "Yard size", options: ["Small", "Medium", "Large"] }] },
  { service: "Junk removal", matches: ["junk", "haul", "appliance", "garage"], startingPrice: 139, time: "Tomorrow · 4–6 PM", detail: "Final volume confirmed before pickup", payment: "Approve final volume before charge", fields: [{ label: "Load size", options: ["A few items", "Half a truck", "A full truck"] }, { label: "Item location", options: ["Curbside", "Garage / ground floor", "Upstairs"] }] },
  { service: "Pressure washing", matches: ["pressure", "driveway", "patio", "siding"], startingPrice: 149, time: "Friday · 1–3 PM", detail: "Surface and access reviewed", payment: "Pay at booking", fields: [{ label: "Surface", options: ["Driveway", "Patio or deck", "Siding or walkway"] }, { label: "Area size", options: ["Small", "Medium", "Large"] }] },
  { service: "Smart home setup", matches: ["smart", "doorbell", "wifi", "wi-fi", "thermostat", "camera"], startingPrice: 129, time: "Thursday · 5:00 PM", detail: "Devices and Wi-Fi reviewed", payment: "Pay at booking", fields: [{ label: "Device", options: ["Doorbell or camera", "Wi-Fi or router", "Thermostat or device"] }, { label: "Already purchased?", options: ["Yes", "No", "Not sure"] }] },
];
const defaultFlow = flows[0];
const guideIntro = "Hey! I can answer questions about our services, timing, and how booking works. When you’re ready, I’ll open the right booking form.";
function findFlow(text: string) { const lower = text.toLowerCase(); return flows.find((flow) => flow.matches.some((match) => lower.includes(match))); }
function makeReply(text: string, flow?: Flow) { const lower = text.toLowerCase(); if (flow) return `${flow.service} starts at $${flow.startingPrice}. ${flow.detail}. Ask anything, or book when you’re ready.`; if (lower.includes("insured") || lower.includes("insurance")) return "Our professionals are presented as insured. Before taking payment live, you’ll want to add your verified coverage details and terms here."; if (lower.includes("what") || lower.includes("service")) return "We can help with cleaning, repairs, mounting, assembly, moving, plumbing, lighting, yard care, and more. Tell me what you have in mind."; return "I can help you think through the job, explain the booking process, or open the right service form when you’re ready."; }

export default function BookingAssistant({ open, requestText, onClose }: { open: boolean; requestText: string; onClose: () => void }) {
  const [entry, setEntry] = useState(""); const [selectedFlow, setSelectedFlow] = useState<Flow>(defaultFlow); const [messages, setMessages] = useState<ChatMessage[]>([{ kind: "guide", text: guideIntro, id: 0 }]); const [formOpen, setFormOpen] = useState(false); const [answers, setAnswers] = useState<Record<string, string>>({}); const [reviewed, setReviewed] = useState(false); const [complete, setComplete] = useState(false); const idRef = useRef(1); const messagesRef = useRef<HTMLDivElement>(null);
  const nextId = () => { const id = idRef.current; idRef.current += 1; return id; };
  useEffect(() => { if (!open) return; setFormOpen(false); setReviewed(false); setComplete(false); setAnswers({}); if (requestText) beginConversation(requestText); else { setSelectedFlow(defaultFlow); setMessages([{ kind: "guide", text: guideIntro, id: 0 }]); } }, [open, requestText]);
  useEffect(() => { if (messagesRef.current) messagesRef.current.scrollTop = messagesRef.current.scrollHeight; }, [messages]);
  function beginConversation(text: string) { const flow = findFlow(text); setEntry(""); if (flow) setSelectedFlow(flow); setMessages([{ kind: "guide", text: guideIntro, id: 0 }, { kind: "user", text, id: nextId() }, { kind: "guide", text: makeReply(text, flow), id: nextId(), flow }]); }
  function submit(event: FormEvent) { event.preventDefault(); const text = entry.trim(); if (text) beginConversation(text); }
  function openForm(flow: Flow) { setSelectedFlow(flow); setAnswers({}); setReviewed(false); setComplete(false); setFormOpen(true); }
  const formReady = selectedFlow.fields.every((field) => answers[field.label]) && answers["Preferred time"] && answers.Name && answers.Email;
  return <><div className={`chat${open ? " open" : ""}`}><div className="chat-head"><div className="agent"><div className="spark">✨</div><div><strong>Good House Guide</strong><div className="online"><b>●</b> Here to help, not rush</div></div></div><button className="x" aria-label="Close chat" onClick={() => { setFormOpen(false); onClose(); }}>×</button></div><div className="messages" ref={messagesRef}>{messages.map((message) => message.kind === "user" ? <div className="bubble user" key={message.id}>{message.text}</div> : <div className="chat-guide" key={message.id}><div className="bubble ai">{message.text}</div>{message.flow && <button className="book-service-link" onClick={() => openForm(message.flow!)}>Book {message.flow.service} <span>→</span></button>}</div>)}</div><form className="chat-form" onSubmit={submit}><input className="chat-input" value={entry} onChange={(event) => setEntry(event.target.value)} placeholder="Ask a question or describe the job..." /><button className="send" aria-label="Send message">↑</button></form></div>
  <div className={`checkout-scrim${formOpen ? " open" : ""}`} onClick={() => setFormOpen(false)}><aside className="checkout-panel" aria-label="Booking form" onClick={(event) => event.stopPropagation()}><div className="checkout-head"><div><div className="eyebrow">Book this service</div><h2>{selectedFlow.service}</h2></div><button className="x" onClick={() => setFormOpen(false)} aria-label="Close booking form">×</button></div>{!complete ? <><div className="checkout-status"><span>1</span><b>Details</b><i /><span>2</span><b>Review</b><i /><span>3</span><b>Checkout</b></div><form className="booking-form" onSubmit={(event) => { event.preventDefault(); if (formReady) setReviewed(true); }}><div className="booking-form-fields">{selectedFlow.fields.map((field) => <label key={field.label}><span>{field.label}</span><select value={answers[field.label] ?? ""} onChange={(event) => setAnswers({ ...answers, [field.label]: event.target.value })}><option value="">Choose one</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select></label>)}<label><span>Preferred time</span><select value={answers["Preferred time"] ?? ""} onChange={(event) => setAnswers({ ...answers, "Preferred time": event.target.value })}><option value="">Choose a time</option><option>{selectedFlow.time}</option><option>First available</option><option>Pick another time</option></select></label><label><span>Your name</span><input value={answers.Name ?? ""} onChange={(event) => setAnswers({ ...answers, Name: event.target.value })} placeholder="Name" /></label><label><span>Email</span><input type="email" value={answers.Email ?? ""} onChange={(event) => setAnswers({ ...answers, Email: event.target.value })} placeholder="you@example.com" /></label></div>{reviewed && <div className="checkout-summary"><div><span>Time</span><strong>{answers["Preferred time"]}</strong></div>{selectedFlow.fields.map((field) => <div key={field.label}><span>{field.label}</span><strong>{answers[field.label]}</strong></div>)}</div>}<div className="checkout-total"><span>Starting at</span><strong>${selectedFlow.startingPrice}</strong><small>{selectedFlow.payment}</small></div>{reviewed ? <button className="btn wide" type="button" onClick={() => setComplete(true)}>Continue to secure checkout →</button> : <button className="btn wide" disabled={!formReady}>Review booking →</button>}<p className="checkout-note">Prototype only—no card will be charged here. A secure payment provider connects at the next step.</p></form></> : <div className="booking-complete"><div className="spark">✓</div><div className="eyebrow">Booking request ready</div><h3>Your {selectedFlow.service.toLowerCase()} plan is ready.</h3><p>The secure checkout step is ready to connect to your payment provider. No payment was taken in this prototype.</p><button className="btn wide" onClick={() => setFormOpen(false)}>Back to chat</button></div>}</aside></div></>;
}
